### ISSUE TITLE
想请你做个外包项目，关于draggable的。

### ISSUE THREAD

**Issue by qxkxzw** [zjffun/vue-shopify-draggable#3]
很抱歉，用这种方式打扰你。

我想请你用draggable做个外包项目，我把我的微信发到你邮箱了，麻烦你有空看一下。

**Comment by zjffun** [comment]
感觉没有精力做外包T_T。加你微信了，业余时间交流交流技术也是极好的。

<img src="https://user-images.githubusercontent.com/25266120/105620068-f1eb3a00-5e33-11eb-84ff-14f28913b430.jpg" width="300">
