### ISSUE TITLE
use plugins

### ISSUE THREAD

**Issue by CavalcanteLeo** [zjffun/vue-shopify-draggable#4]
How to use plugins when register as global component?

```js
import Vue from 'vue'
import VueShopifyDraggable from 'vue-shopify-draggable'
Vue.use(VueShopifyDraggable)
```

component:
```js
<script>
  export default {
    data() {
      return {
        options: {
          draggable: '.item',
          sortAnimation: {
            duration: 200,
            easingFunction: 'ease-in-out',
          },
          plugins: [Draggable.Plugins.SortAnimation], // <-- 'Draggable' is not defined. eslint no-undef
        },
      },
    },
    methods: {
      sorted: function (e) {
        console.log(e)
      }
    }
  }
</script>

```

I kwon i can import as `import * as Draggable from '@shopify/draggable/lib/draggable'`, but in this case, I'm importing it twice.
And even if I import like that, then `SortAnimation` will not be defined

**Comment by zjffun** [comment]
It seems that import draggable plugins is confusing. `@shopify/draggable/lib/draggable` does not export the SortAnimation plugin. Use the following code can import it.

```js
import { SortAnimation } from "@shopify/draggable/lib/plugins.js";
// or
import { Plugins } from '@shopify/draggable';
Plugins.SortAnimation
```

Exmaple: https://codesandbox.io/s/vue-shopify-draggable--sortable-3yng4

vue-shopify-draggable internally import `@shopify/draggable`. So if you also import `@shopify/draggable`, webpack will automatically treat those import as the same and only package one in bundle.

**Comment by CavalcanteLeo** [comment]
thanks
